In [5]:
run QIRN_GUI.py


ModuleNotFoundError: No module named 'Scripts'

In [3]:
QIRN('IntermediatesDatabase.csv','NetworkBuilder_SulfurExample.csv','ReactionDatabase.csv',100,0.1)

FileNotFoundError: [Errno 2] No such file or directory: 'IntermediatesDatabase.csv'

In [7]:
metanetwork

{'EC 1.1.1.1': [array([0.0186, 0.0186, 0.0186, 0.0186]),
  array([0., 0., 0., 0.]),
  'acetaldehyde',
  '',
  'ethanol',
  '',
  '0.186',
  '0',
  0,
  0,
  'Alcohol dehydrogenase'],
 'EC 1.1.1.37': [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'malate',
  '',
  'oxaloacetate',
  '',
  '0',
  '0',
  0,
  0,
  'Malate Dehydrogenase'],
 'EC 1.1.1.39': [array([4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05,
         4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05, 4.e-05]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'malate',
  '',
  'pyruvate',
  'co2_malic',
  '0.0004',
  '0',
  0,
  0,
  'Malic Enzyme'],
 'EC 1.1.1.41': [array([0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001,
         0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001,
         0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 

In [16]:
import csv
with open('eggs.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
         


TypeError: open() got an unexpected keyword argument 'newline'

In [3]:
phi = 0
molecule = 'serine'
nC = intmed[molecule][0]
conc = intmed[molecule][2]
intra = np.zeros(nC)

for iC in range(nC):
    cumu_ratio=QIRNfile.GetSingleRatio(conc,iC)
    cumu_dC=QIRNfile.GetDelta(cumu_ratio)
    intra[iC] = cumu_dC

serine_intra = np.vstack((serine_intra,intra))
print(serine_intra[1,:])

[-26.529 -26.535 -26.535]


In [4]:
molecule = 'fructose-6-phosphate_cytoplasm'
nC = intmed[molecule][0]
conc = intmed[molecule][2]
intra = np.zeros(nC)
for iC in range(nC):
    cumu_ratio=QIRNfile.GetSingleRatio(conc,iC)
    cumu_dC=QIRNfile.GetDelta(cumu_ratio)
    intra[iC] = cumu_dC
f6pcyto_intra = np.vstack((f6pcyto_intra,intra))
print(f6pcyto_intra)

molecule = 'fructose-6-phosphate_cytoplasm_aldolase'
nC = intmed[molecule][0]
conc = intmed[molecule][2]
intra = np.zeros(nC)
for iC in range(nC):
    cumu_ratio=QIRNfile.GetSingleRatio(conc,iC)
    cumu_dC=QIRNfile.GetDelta(cumu_ratio)
    intra[iC] = cumu_dC
f6paldo_intra = np.vstack((f6paldo_intra,intra))
print(f6paldo_intra)

[[  0.      0.      0.      0.      0.      0.   ]
 [-26.387 -26.193 -19.928 -12.224 -26.388 -26.395]]
[[  0.      0.      0.      0.      0.      0.   ]
 [-26.394 -26.589 -28.854 -26.706 -27.73  -26.369]]


In [5]:
# Import writer class from csv module
import pandas as pd
outputfile = 'glucoseintra_tcherkez_PR.csv'
Csites = np.linspace(1,6,6)
df_cyto = pd.DataFrame({'F6P Cytoplasm': Csites,
                   'Phi 0.5 T = 0.028': f6pcyto_intra[1,:]
                   })
df_aldo = pd.DataFrame({'F6P Aldolase': Csites,
                   'Phi 0.5 T = 0.028': f6paldo_intra[1,:]
                   })
df_cyto = df_cyto.T
df_aldo = df_aldo.T



df_cyto.to_csv(outputfile, mode='a', index=True, header=False)  
df_aldo.to_csv(outputfile, mode='a', index=True, header=False)  


In [19]:
a = [np.linspace(1,6,6),'Vc/Vo']

print(a)

[array([1., 2., 3., 4., 5., 6.]), 'Vc/Vo']


In [13]:
f6pcyto_intra[1,:]

array([-24.27 , -24.39 , -18.029,  -9.604, -24.497, -24.28 ])

In [7]:
file = 'testfile.csv'
count = 0
for i in file:
    if i == '.':
        value = count
        print(value)
    count += 1
filename = file[0:value]
print(filename)

8
testfile
